/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRepositoryAnalyzeRouteImport } from './routes/_authenticated/repository/analyze'
import { Route as AuthenticatedDocsSpecIdRouteImport } from './routes/_authenticated/docs.$specId'
import { Route as AuthenticatedChatSpecIdRouteImport } from './routes/_authenticated/chat.$specId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepositoryAnalyzeRoute =
  AuthenticatedRepositoryAnalyzeRouteImport.update({
    id: '/repository/analyze',
    path: '/repository/analyze',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocsSpecIdRoute = AuthenticatedDocsSpecIdRouteImport.update({
  id: '/docs/$specId',
  path: '/docs/$specId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatSpecIdRoute = AuthenticatedChatSpecIdRouteImport.update({
  id: '/chat/$specId',
  path: '/chat/$specId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/chat/$specId': typeof AuthenticatedChatSpecIdRoute
  '/docs/$specId': typeof AuthenticatedDocsSpecIdRoute
  '/repository/analyze': typeof AuthenticatedRepositoryAnalyzeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/chat/$specId': typeof AuthenticatedChatSpecIdRoute
  '/docs/$specId': typeof AuthenticatedDocsSpecIdRoute
  '/repository/analyze': typeof AuthenticatedRepositoryAnalyzeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/chat/$specId': typeof AuthenticatedChatSpecIdRoute
  '/_authenticated/docs/$specId': typeof AuthenticatedDocsSpecIdRoute
  '/_authenticated/repository/analyze': typeof AuthenticatedRepositoryAnalyzeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/chat/$specId'
    | '/docs/$specId'
    | '/repository/analyze'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/chat/$specId'
    | '/docs/$specId'
    | '/repository/analyze'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/chat/$specId'
    | '/_authenticated/docs/$specId'
    | '/_authenticated/repository/analyze'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repository/analyze': {
      id: '/_authenticated/repository/analyze'
      path: '/repository/analyze'
      fullPath: '/repository/analyze'
      preLoaderRoute: typeof AuthenticatedRepositoryAnalyzeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/docs/$specId': {
      id: '/_authenticated/docs/$specId'
      path: '/docs/$specId'
      fullPath: '/docs/$specId'
      preLoaderRoute: typeof AuthenticatedDocsSpecIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$specId': {
      id: '/_authenticated/chat/$specId'
      path: '/chat/$specId'
      fullPath: '/chat/$specId'
      preLoaderRoute: typeof AuthenticatedChatSpecIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedChatSpecIdRoute: typeof AuthenticatedChatSpecIdRoute
  AuthenticatedDocsSpecIdRoute: typeof AuthenticatedDocsSpecIdRoute
  AuthenticatedRepositoryAnalyzeRoute: typeof AuthenticatedRepositoryAnalyzeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedChatSpecIdRoute: AuthenticatedChatSpecIdRoute,
  AuthenticatedDocsSpecIdRoute: AuthenticatedDocsSpecIdRoute,
  AuthenticatedRepositoryAnalyzeRoute: AuthenticatedRepositoryAnalyzeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
